SELECT * FROM CIDADES;

SELECT * FROM PREFEITOS;

-- SOMENTE A INTERSECÇÃO
SELECT * FROM CIDADES C
INNER JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;

-- INTERSECÇÃO + ESQUERDA (TODAS AS CIDADES)
SELECT * FROM CIDADES C
LEFT JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;

-- INTERSECÇÃO + DIREITA (TODOS OS PREFEITOS)
SELECT * FROM CIDADES C
RIGHT OUTER JOIN PREFEITOS P
ON C.ID = P.CIDADE_ID;

-- LEFT JOIN = LEFT OUTER JOIN
-- RIGHT JOIN = RIGHT OUTER JOIN

-- SIMULAR O FULL JOIN NO MYSQL:
SELECT * FROM CIDADES C LEFT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID
UNION
SELECT * FROM CIDADES C RIGHT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;

-- EXISTEM DUAS INTERSECÇÕES IGUAIS, O UNION NÃO TRAZ LINHAS\
-- DUPLICADAS, CASO QUEIRA MESMO ASSIM, UTILEZE: UNION ALL