SELECT
	C.NOME   AS 'Cidade',
    E.NOME   AS 'Estado',
    E.REGIAO AS 'Região'
FROM ESTADOS E, CIDADES C
WHERE C.ESTADO_ID = E.ID;

-- EQUIVALENTE USANDO INNER JOIN:

SELECT
	C.NOME   AS 'Cidade',
    E.NOME   AS 'Estado',
    E.REGIAO AS 'Região'
FROM ESTADOS E
INNER JOIN CIDADES C ON C.ESTADO_ID = E.ID;