CREATE TABLE IF NOT EXISTS EMPRESAS (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CNPJ INT UNSIGNED,
    UNIQUE KEY (CNPJ),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS EMPRESAS_UNIDADES (
	CIDADE_ID INT UNSIGNED NOT NULL,
    EMPRESA_ID INT UNSIGNED NOT NULL,
    SEDE TINYINT NOT NULL,
    PRIMARY KEY (CIDADE_ID, EMPRESA_ID)
);