INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Campinas', 795, 32);

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Niterói', 133.9, 26);

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES (
	'Caruaru',
    920.6,
    (SELECT ID FROM ESTADOS WHERE SIGLA = 'PE')
);

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES (
	'Juazeiro do Norte',
    248.2,
    (SELECT ID FROM ESTADOS WHERE SIGLA = 'CE')
);