INSERT INTO ESTADOS (ID, NOME, SIGLA, REGIAO, POPULACAO)
VALUES (1000, 'Novo', 'NV', 'Sul', 2.54);
    
SELECT * FROM ESTADOS;

INSERT INTO ESTADOS(NOME, SIGLA, REGIAO, POPULACAO)
VALUES ('Mais Novo', 'MN', 'Norte', 2.51);